notifier filter for completed trades
carlos8f/zenbot pull request #1754
Opened 2018-10-30 07:19 UTC by BaybarsGUCLU

when ı use notifer for seing my trades data, canceled orders become so big waste, then ı create a filter to zenbot for sending notifier only completed messages.

2018-10-30 10:31 UTC, DeviaVir commented on commands/trade.js
> +    .option('--only_completed_trades', 'Message filter for only completed trades to notifier.', Boolean, conf.notifiers.only_completed_trades)
I don't think we should add this, but just keep it as a `conf` option instead.

2018-10-30 10:40 UTC, DeviaVir requested changes
some more things

2018-10-30 10:40 UTC, DeviaVir commented on lib/engine.js
> +              if(!so.only_completed_trades){
this should probably be 
```suggestion
              if(!so.notifiers.only_completed_trades){
```

2018-10-30 10:40 UTC, DeviaVir commented on lib/engine.js
> +              if(!so.only_completed_trades){
```suggestion
              if(!so.notifiers.only_completed_trades){
```

2018-10-30 10:40 UTC, DeviaVir commented on commands/trade.js
> +      so.only_completed_trades = conf.only_completed_trades
I think you can leave this out entirely.
```suggestion
      
```

2018-10-30 12:10 UTC, BaybarsGUCLU commented
Mister, sorry about i taken your time. i don't understand, there is no problem on my repository. Could you explain me about this case?

2018-10-31 08:20 UTC, DeviaVir approved these changes

2018-10-31 08:24 UTC, merged